-- MySQL Script generated by MySQL Workbench
-- 06/17/16 08:36:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema curriculum_hipertec
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema curriculum_hipertec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `curriculum_hipertec` DEFAULT CHARACTER SET utf8 ;
USE `curriculum_hipertec` ;

-- -----------------------------------------------------
-- Table `curriculum_hipertec`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculum_hipertec`.`aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobreNome` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `nacionalidade` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(2) NOT NULL,
  `foto` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `linkedin` VARCHAR(45) NULL,
  `facebook` VARCHAR(45) NULL,
  `cpf` VARCHAR(14) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curriculum_hipertec`.`curriculum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculum_hipertec`.`curriculum` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aluno_id` INT NOT NULL,
  `resumo` TEXT(200) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_curriculum_aluno_idx` (`aluno_id` ASC),
  CONSTRAINT `fk_curriculum_aluno`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `curriculum_hipertec`.`aluno` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curriculum_hipertec`.`experiencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculum_hipertec`.`experiencias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empresa` VARCHAR(45) NOT NULL,
  `funcao` VARCHAR(45) NOT NULL,
  `inicio` DATE NOT NULL,
  `fim` DATE NULL,
  `curriculum_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_experiencias_curriculum1_idx` (`curriculum_id` ASC),
  CONSTRAINT `fk_experiencias_curriculum1`
    FOREIGN KEY (`curriculum_id`)
    REFERENCES `curriculum_hipertec`.`curriculum` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curriculum_hipertec`.`competencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculum_hipertec`.`competencias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `curso` VARCHAR(45) NOT NULL,
  `instituicao` VARCHAR(45) NOT NULL,
  `cargahoraria` INT NOT NULL,
  `nivel` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `curriculum_id` INT NOT NULL,
  `conclusao` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_competencias_curriculum1_idx` (`curriculum_id` ASC),
  CONSTRAINT `fk_competencias_curriculum1`
    FOREIGN KEY (`curriculum_id`)
    REFERENCES `curriculum_hipertec`.`curriculum` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curriculum_hipertec`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculum_hipertec`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `cep` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `aluno` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_endereco_aluno1_idx` (`aluno` ASC),
  CONSTRAINT `fk_endereco_aluno1`
    FOREIGN KEY (`aluno`)
    REFERENCES `curriculum_hipertec`.`aluno` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `curriculum_hipertec`.`informacaoAdicional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculum_hipertec`.`informacaoAdicional` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` TEXT(300) NOT NULL,
  `curriculum_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_informacaoAdicional_curriculum1_idx` (`curriculum_id` ASC),
  CONSTRAINT `fk_informacaoAdicional_curriculum1`
    FOREIGN KEY (`curriculum_id`)
    REFERENCES `curriculum_hipertec`.`curriculum` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
